### ISSUE TITLE
Docs? 

### ISSUE THREAD

**Issue by Hunter2807** [plasticuproject/cleverbotfree#14]
Hey! 

I want to use your module, and I want some docs to use the bot. Are there any docs or something for it? I want to embed this into a discord bot...

**Comment by plasticuproject** [comment]
I didn't really feel a need to make any documentation for this, as it's pretty simple, only does a couple things, and most everything is covered in the installation and example in the README.md

The easiest way to add this to a discord bot using discord.py would be something like:
```python
import discord
from discord.ext import commands
from cleverbotfree.cbfree import Cleverbot

bot = commands.Bot(command_prefix='&')
send_cb = Cleverbot().single_exchange

@bot.command()
async def chat(ctx, *args):
    user_input = ' '.join(args)
    response = send_cb(user_input)
    await ctx.send(response)
 ```

**Comment by Hunter2807** [comment]
Oh ok. Thanks!

**Comment by plasticuproject** [comment]
Using the code I posted above, when a user queries the bot it will open up a headless browser on the server running your bot that will stay open. Every time someone queries the bot after that it will send the data to headless browser, and they will get a response from the bot in discord until your bot application is closed.

**Comment by Hunter2807** [comment]
So I should just remove that `single_exchange` thingy?

**Comment by plasticuproject** [comment]
No, use the function I posted above, it works. single_exchange works because the discord code is asynchronous.  The headless browser will close when you when you exit your discord bot application.

You're delving into implementation territory with your questions now. My examples show basic usage with this module, you'll have to poke around to figure out how to implement it with various frameworks on your own, as it's out of scope of what this module is by itself. This module is just a very basic, limited api to interface the cleverbot website with python.

Here is an example of how I used this module in a discord bot that I created.
https://github.com/plasticuproject/clevercord

**Comment by Hunter2807** [comment]
Hey @plasticuproject, when I used this, I got a biiig error in my repl.it . Is it something like I can't use it with repl?

**Comment by plasticuproject** [comment]
Please read the README.md
This module requires you to set up firefox, gekodriver, and selenium. You can't run this on some sandbox webapp, it needs to be run from a server or PC.

I'm closing this issue out as there is no underlying issue here.
